### PR TITLE
target/p256: add a few more corpus entries

### PR DESCRIPTION
**Pull request by josharian**

### CODE REVIEW

**Comment by mmcloughlin** [comment]
Actually, I ran against P-256 and SHA3 for a while so I think I have some corpus entries sitting on S3 that I didn't commit. Let me go find them.

**Comment by josharian** [comment]
> Actually, I ran against P-256 and SHA3 for a while so I think I have some corpus entries sitting on S3 that I didn't commit. Let me go find them.

Cool. A few duplicate corpus entries won't hurt too much, I think.

**Comment by mmcloughlin** [comment]
Okay, committed them.

Out of interest, are you using a personal computer, or did you try out the terraform EC2 config?

**Comment by josharian** [comment]
Personal computer. I'm hacking on go-fuzz, and using this as one of my test cases, since it is nicely packaged up, and since it is a relatively hard case from a fuzzer's perspective.

**Comment by mmcloughlin** [comment]
Oh, sounds great. Well I appreciate the contributions, it's good to get more eyeballs on this project and Go crypto in general.

`go-fuzz` is such an easy project to use so I thought it was a good place to start, but I did have some doubts about it's effectiveness on targets such as these. Specifically:

* Crypto algorithms typically have minimal structure to their inputs (unlike a network protocol or language syntax)
* To my knowledge, `go-fuzz` has no visibility into the coverage of assembly functions

As someone with more insight into `go-fuzz`, what would you say to these concerns?

**Comment by josharian** [comment]
> * Crypto algorithms typically have minimal structure to their inputs (unlike a network protocol or language syntax)

Dmitry can speak more authoritatively, but go-fuzz will still work on these, just be less efficient.

> * To my knowledge, `go-fuzz` has no visibility into the coverage of assembly functions

It can still use the Go implementation to guide coverage. If they have similar structures, it'll probably suffice.

**Comment by dvyukov** [comment]
Absence of input structure should not be a problem.
Absence of coverage, or partial coverage, reduces fuzzing efficiency, but it still can find bugs. Some of out fuzzers that don't have coverage are still finding hundreds of bugs.
For some libraries that have optimized asm implementations and generic C implementations, we switched the build to C implementations for fuzzing (also possible to runs 2 side-by-side, even compare results of both implementations).
Some crypto algorithms are completely oblivious to the input data, though. Whatever is passed in just does not affect anything in the algorithm. These are less useful to fuzz, but that's for good.

**Comment by mmcloughlin** [comment]
Thank you both.

> For some libraries that have optimized asm implementations and generic C implementations, we switched the build to C implementations for fuzzing (also possible to runs 2 side-by-side, even compare results of both implementations).

This is an interesting idea. To clarify, do you mean:

* Call the C reference implementation with `cgo` and fuzz with `go-fuzz`
* Expose the Go asm version to C (somehow) and fuzz with `afl` (or similar)

**Comment by dvyukov** [comment]
I was talking about testing C libraries that have asm. For Go libraries this corresponds to switching from asm to Go impl which is natively understood by go-fuzz (assuming you have corresponding Go implementations for side-by-side testing, etc). But testing Go (or asm) against C impl is possible too, e.g. I fuzzed regexp package against re2 side-by-side, which is super useful as it finds logical bugs, not just crashes.

**Comment by dgryski** [comment]
I've similarly fuzzed (via cgo) my Go version of farmhash against the reference C implementation.  Found a few compatibility issues mostly around automatic integer promotion that needed to be explicitly handled in Go.

**Pull request merged**
